// `value` = canonical French name stored in DB; `ar` = display in Arabic locale; `code` = 2-digit official code for ville cascade
export const WILAYAS: { value: string; ar: string; code: string }[] = [
  { value: 'Adrar', ar: 'أدرار', code: '01' },
  { value: 'Chlef', ar: 'الشلف', code: '02' },
  { value: 'Laghouat', ar: 'الأغواط', code: '03' },
  { value: 'Oum El Bouaghi', ar: 'أم البواقي', code: '04' },
  { value: 'Batna', ar: 'باتنة', code: '05' },
  { value: 'Béjaïa', ar: 'بجاية', code: '06' },
  { value: 'Biskra', ar: 'بسكرة', code: '07' },
  { value: 'Béchar', ar: 'بشار', code: '08' },
  { value: 'Blida', ar: 'البليدة', code: '09' },
  { value: 'Bouira', ar: 'البويرة', code: '10' },
  { value: 'Tamanrasset', ar: 'تمنراست', code: '11' },
  { value: 'Tébessa', ar: 'تبسة', code: '12' },
  { value: 'Tlemcen', ar: 'تلمسان', code: '13' },
  { value: 'Tiaret', ar: 'تيارت', code: '14' },
  { value: 'Tizi Ouzou', ar: 'تيزي وزو', code: '15' },
  { value: 'Alger', ar: 'الجزائر', code: '16' },
  { value: 'Djelfa', ar: 'الجلفة', code: '17' },
  { value: 'Jijel', ar: 'جيجل', code: '18' },
  { value: 'Sétif', ar: 'سطيف', code: '19' },
  { value: 'Saïda', ar: 'سعيدة', code: '20' },
  { value: 'Skikda', ar: 'سكيكدة', code: '21' },
  { value: 'Sidi Bel Abbès', ar: 'سيدي بلعباس', code: '22' },
  { value: 'Annaba', ar: 'عنابة', code: '23' },
  { value: 'Guelma', ar: 'قالمة', code: '24' },
  { value: 'Constantine', ar: 'قسنطينة', code: '25' },
  { value: 'Médéa', ar: 'المدية', code: '26' },
  { value: 'Mostaganem', ar: 'مستغانم', code: '27' },
  { value: "M'Sila", ar: 'المسيلة', code: '28' },
  { value: 'Mascara', ar: 'معسكر', code: '29' },
  { value: 'Ouargla', ar: 'ورقلة', code: '30' },
  { value: 'Oran', ar: 'وهران', code: '31' },
  { value: 'El Bayadh', ar: 'البيض', code: '32' },
  { value: 'Illizi', ar: 'إليزي', code: '33' },
  { value: 'Bordj Bou Arréridj', ar: 'برج بوعريريج', code: '34' },
  { value: 'Boumerdès', ar: 'بومرداس', code: '35' },
  { value: 'El Tarf', ar: 'الطارف', code: '36' },
  { value: 'Tindouf', ar: 'تندوف', code: '37' },
  { value: 'Tissemsilt', ar: 'تيسمسيلت', code: '38' },
  { value: 'El Oued', ar: 'الوادي', code: '39' },
  { value: 'Khenchela', ar: 'خنشلة', code: '40' },
  { value: 'Souk Ahras', ar: 'سوق أهراس', code: '41' },
  { value: 'Tipaza', ar: 'تيبازة', code: '42' },
  { value: 'Mila', ar: 'ميلة', code: '43' },
  { value: 'Aïn Defla', ar: 'عين الدفلى', code: '44' },
  { value: 'Naâma', ar: 'النعامة', code: '45' },
  { value: 'Aïn Témouchent', ar: 'عين تموشنت', code: '46' },
  { value: 'Ghardaïa', ar: 'غرداية', code: '47' },
  { value: 'Relizane', ar: 'غليزان', code: '48' },
  { value: 'Timimoun', ar: 'تيميمون', code: '49' },
  { value: 'Bordj Badji Mokhtar', ar: 'برج باجي مختار', code: '50' },
  { value: 'Ouled Djellal', ar: 'أولاد جلال', code: '51' },
  { value: 'Béni Abbès', ar: 'بني عباس', code: '52' },
  { value: 'In Salah', ar: 'عين صالح', code: '53' },
  { value: 'In Guezzam', ar: 'عين قزام', code: '54' },
  { value: 'Touggourt', ar: 'تقرت', code: '55' },
  { value: 'Djanet', ar: 'جانت', code: '56' },
  { value: "El M'Ghair", ar: 'المغير', code: '57' },
  { value: 'El Meniaa', ar: 'المنيعة', code: '58' },
];
